### ISSUE TITLE
Async Workflows

### ISSUE THREAD

**Issue by atymic** [nocode-js/sequential-workflow-machine#10]
Hey! Does this support workflows that are async, for example a chatbot. Where the workflow state can be persisted, then resumed?

**Comment by b4rtaz** [comment]
Hello @atymic!

Now the engine doesn't support it. But you may achieve it in hacky way. Your activity should throw a well known error. This will stop the workflow machine. Then you can dump the state to your storage. To resume the workflow you need to pass the `initialStepId` parameter to [WorkflowMachineBuilder](https://github.com/nocode-js/sequential-workflow-machine/blob/main/machine/src/workflow-machine-builder.ts) and reuse the previous state.

**Comment by b4rtaz** [comment]
I think [0.7.1](https://github.com/nocode-js/sequential-workflow-machine/releases/tag/v0.7.1) provides some solution for this problem.
